apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: biseras/backend
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: 127.0.0.1:8080