name: Login to Docker, build, tag, push and AWS Deploy
on: [push]

jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v2
    
#         - name: Login to DockerHub
#           uses: docker/login-action@v1
#           with:
#             username: ${{ secrets.DOCKERHUB_USERNAME }}
#             password: ${{ secrets.DOCKERHUB_TOKENN }}
        
#         - name: Build database image
#           run: |
#             docker build -t biseras/database ./
            
#         - name: Build backend image
#           run: |
#             docker build -t biseras/backend ./backend
        
#         - name: Docker push database image
#           run: |
#             docker push biseras/database
        
#         - name: Docker push backend image
#           run: |
#             docker push biseras/backend
            
    deploy:
#         needs: build
        runs-on: self-hosted
        steps: 
        - uses: actions/checkout@v2
        - name: deploy
          run: |
            pwd
            cd..
            pwd
            ls

